home:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: host.docker.internal
    port: 3306
    database: home
    username: root
    password: root

  redis:
    host: host.docker.internal
    port: 6379
    password: root

  logging:
    level: INFO

  mybatis:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl