fyrn:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: host.docker.internal
    port: 3306
    database: fyrn
    username: root
    password: root

  redis:
    host: host.docker.internal
    port: 6379
    password: root

  oss:
    protocol: s3
    access-key-id: eZkIBk8WaWlfxjCx5OAW
    access-key-secret: 5smkTin7spqzPpfHH82UphdBS2YBhr1W3f1muzUT
    bucket-name: fyrn
    endpoint: http://host.docker.internal:9000
    region: us-east-1

  logging:
    level: INFO

  mybatis:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl